insert

$keyword78 isa keyword, has hashtag "electrophysiology";
$keyword45 isa keyword, has hashtag "biologging";
$keyword80 isa keyword, has hashtag "ethics";
$keyword79 isa keyword, has hashtag "ecology";
$keyword69 isa keyword, has hashtag "disease";
$keyword75 isa keyword, has hashtag "exercise";
$keyword82 isa keyword, has hashtag "biologgers";
$keyword50 isa keyword, has hashtag "accelerometry";
$keyword46 isa keyword, has hashtag "birds";
$keyword49 isa keyword, has hashtag "climate";
$keyword77 isa keyword, has hashtag "hormones";
$keyword83 isa keyword, has hashtag "fightorflight";
$keyword84 isa keyword, has hashtag "adrenaline";
$keyword65 isa keyword, has hashtag "squirrel";
$keyword47 isa keyword, has hashtag "lifehistory";
$keyword51 isa keyword, has hashtag "oscillations";
$keyword52 isa keyword, has hashtag "delta";
$keyword53 isa keyword, has hashtag "memory";
$keyword86 isa keyword, has hashtag "cns";
$keyword66 isa keyword, has hashtag "energetics";
$keyword67 isa keyword, has hashtag "behavior";
$keyword63 isa keyword, has hashtag "respiration";
$keyword64 isa keyword, has hashtag "immunity";
$keyword55 isa keyword, has hashtag "athletics";
$keyword62 isa keyword, has hashtag "depression";
$keyword68 isa keyword, has hashtag "clinical";
$keyword70 isa keyword, has hashtag "parkinsons";
$keyword71 isa keyword, has hashtag "stroke";
$keyword72 isa keyword, has hashtag "statistics";
$keyword56 isa keyword, has hashtag "fitness";
$keyword74 isa keyword, has hashtag "pharmacology";
$keyword58 isa keyword, has hashtag "children";
$keyword59 isa keyword, has hashtag "obesity";
$keyword60 isa keyword, has hashtag "reactivity";
$keyword42 isa keyword, has hashtag "stress";
$keyword34 isa keyword, has hashtag "parasympathetic";
$keyword48 isa keyword, has hashtag "conservation";
$keyword76 isa keyword, has hashtag "glucocorticoids";
$keyword38 isa keyword, has hashtag "neural";
$keyword33 isa keyword, has hashtag "sympathetic";
$keyword40 isa keyword, has hashtag "fear";
$keyword39 isa keyword, has hashtag "emotion";
$keyword37 isa keyword, has hashtag "vagalnerve";
$keyword31 isa keyword, has hashtag "autonomic";
$keyword35 isa keyword, has hashtag "norepinephrine";
$keyword36 isa keyword, has hashtag "acetylcholine";
$keyword43 isa keyword, has hashtag "adaptation";
$keyword44 isa keyword, has hashtag "neuroimaging";
$keyword41 isa keyword, has hashtag "survival";
$keyword81 isa keyword, has hashtag "neuroscience";
$keyword30 isa keyword, has hashtag "hrv";
$keyword54 isa keyword, has hashtag "sleep";
$keyword57 isa keyword, has hashtag "training";
$keyword87 isa keyword, has hashtag "gender";
$keyword73 isa keyword, has hashtag "methods";
$source23 isa source, has title "Dietary sodium influences the effect of mental stress on heart rate variability: a randomized trial in healthy adults", has authors "Alexander R. Allen";
$connection1 (data: $source23, topic: $keyword30) isa connection;
$connection2 (data: $source23, topic: $keyword31) isa connection;
$connection3 (data: $source23, topic: $keyword42) isa connection;
$source31 isa source, has title "Effect of a Weight Reduction Program on Baseline and Stress-Induced Heart Rate Variability in Children with Obesity", has authors "Nazar Mazurak";
$connection4 (data: $source31, topic: $keyword30) isa connection;
$connection5 (data: $source31, topic: $keyword31) isa connection;
$connection6 (data: $source31, topic: $keyword42) isa connection;
$connection7 (data: $source31, topic: $keyword58) isa connection;
$connection8 (data: $source31, topic: $keyword59) isa connection;
$connection9 (data: $source31, topic: $keyword60) isa connection;
$connection10 (data: $source31, topic: $keyword73) isa connection;
$source27 isa source, has title "Using accelerometers to remotely and automatically characterize behavior in small animals", has authors "Talisin T. Hammond";
$connection11 (data: $source27, topic: $keyword50) isa connection;
$connection12 (data: $source27, topic: $keyword67) isa connection;
$connection13 (data: $source27, topic: $keyword82) isa connection;
$source40 isa source, has title "A model of neurovisceral integration in emotion regulation and dysregulation", has authors "Julian F. Thayer";
$connection14 (data: $source40, topic: $keyword39) isa connection;
$connection15 (data: $source40, topic: $keyword81) isa connection;
$source36 isa source, has title "Heart Rate Variability Today", has authors "Borejda Xhyheri";
$connection16 (data: $source36, topic: $keyword30) isa connection;
$connection17 (data: $source36, topic: $keyword54) isa connection;
$connection18 (data: $source36, topic: $keyword57) isa connection;
$connection19 (data: $source36, topic: $keyword73) isa connection;
$connection20 (data: $source36, topic: $keyword87) isa connection;
$source45 isa source, has title "Glucocorticoids and “Stress” Are Not Synonymous", has authors "S. A. MacDougall Shackleton";
$connection21 (data: $source45, topic: $keyword42) isa connection;
$connection22 (data: $source45, topic: $keyword76) isa connection;
$connection23 (data: $source45, topic: $keyword77) isa connection;
$source21 isa source, has title "Integrating physiology, behavior, and energetics: Biologging in a free-living arctic hibernator", has authors "Cory T. Williams";
$connection24 (data: $source21, topic: $keyword45) isa connection;
$connection25 (data: $source21, topic: $keyword48) isa connection;
$connection26 (data: $source21, topic: $keyword50) isa connection;
$connection27 (data: $source21, topic: $keyword60) isa connection;
$connection28 (data: $source21, topic: $keyword65) isa connection;
$connection29 (data: $source21, topic: $keyword66) isa connection;
$connection30 (data: $source21, topic: $keyword67) isa connection;
$source35 isa source, has title "A meta-analysis of heart rate variability and neuroimaging studies: Implications for heart rate variability as a marker of stress and health", has authors "Julian F. Thayer";
$connection31 (data: $source35, topic: $keyword31) isa connection;
$connection32 (data: $source35, topic: $keyword41) isa connection;
$connection33 (data: $source35, topic: $keyword36) isa connection;
$connection34 (data: $source35, topic: $keyword42) isa connection;
$connection35 (data: $source35, topic: $keyword40) isa connection;
$connection36 (data: $source35, topic: $keyword34) isa connection;
$connection37 (data: $source35, topic: $keyword73) isa connection;
$connection38 (data: $source35, topic: $keyword39) isa connection;
$connection39 (data: $source35, topic: $keyword38) isa connection;
$connection40 (data: $source35, topic: $keyword30) isa connection;
$connection41 (data: $source35, topic: $keyword44) isa connection;
$connection42 (data: $source35, topic: $keyword37) isa connection;
$connection43 (data: $source35, topic: $keyword43) isa connection;
$connection44 (data: $source35, topic: $keyword35) isa connection;
$connection45 (data: $source35, topic: $keyword33) isa connection;
$source24 isa source, has title "Inclusion of Respiratory Frequency Information in Heart Rate Variability Analysis for Stress Assessment", has authors "Alberto Hernando";
$connection46 (data: $source24, topic: $keyword30) isa connection;
$connection47 (data: $source24, topic: $keyword42) isa connection;
$connection48 (data: $source24, topic: $keyword63) isa connection;
$connection49 (data: $source24, topic: $keyword64) isa connection;
$connection50 (data: $source24, topic: $keyword73) isa connection;
$source37 isa source, has title "Measures of physiological stress: a transparent or opaque window into the status, management and conservation of species?", has authors "Ben Dantzer";
$connection51 (data: $source37, topic: $keyword42) isa connection;
$connection52 (data: $source37, topic: $keyword48) isa connection;
$connection53 (data: $source37, topic: $keyword76) isa connection;
$source41 isa source, has title "Heart rate variability Standards of measurement, physiological interpretation, and clinical use", has authors "The European Society of Cardiology";
$connection54 (data: $source41, topic: $keyword73) isa connection;
$connection55 (data: $source41, topic: $keyword70) isa connection;
$connection56 (data: $source41, topic: $keyword56) isa connection;
$connection57 (data: $source41, topic: $keyword71) isa connection;
$connection58 (data: $source41, topic: $keyword69) isa connection;
$connection59 (data: $source41, topic: $keyword30) isa connection;
$connection60 (data: $source41, topic: $keyword74) isa connection;
$connection61 (data: $source41, topic: $keyword72) isa connection;
$connection62 (data: $source41, topic: $keyword68) isa connection;
$connection63 (data: $source41, topic: $keyword75) isa connection;
$source34 isa source, has title "Biologging technologies: new tools for conservation. Introduction", has authors "Steven J. Bograd";
$connection64 (data: $source34, topic: $keyword45) isa connection;
$connection65 (data: $source34, topic: $keyword47) isa connection;
$connection66 (data: $source34, topic: $keyword48) isa connection;
$connection67 (data: $source34, topic: $keyword49) isa connection;
$connection68 (data: $source34, topic: $keyword50) isa connection;
$source29 isa source, has title "A phylogenetically controlled meta-analysis of biologging device effects on birds: Deleterious effects and a call for more standardized reporting of study data", has authors "Thomas W. Bodey";
$connection69 (data: $source29, topic: $keyword45) isa connection;
$connection70 (data: $source29, topic: $keyword46) isa connection;
$connection71 (data: $source29, topic: $keyword47) isa connection;
$source46 isa source, has title "Evaluation of Cardiac Responses to Stress in Healthy Individuals - A Non Invasive Evaluation by Heart Rate Variability and Stroop Test", has authors "Chiranjeevi Kumar Endukuru";
$connection72 (data: $source46, topic: $keyword73) isa connection;
$source39 isa source, has title "Competing Roles of Slow Oscillations and Delta Waves in Memory Consolidation versus Forgetting", has authors "Karunesh Ganguly";
$connection73 (data: $source39, topic: $keyword51) isa connection;
$connection74 (data: $source39, topic: $keyword52) isa connection;
$connection75 (data: $source39, topic: $keyword53) isa connection;
$connection76 (data: $source39, topic: $keyword54) isa connection;
$source30 isa source, has title "ONEIROS, a new miniature standalone device for recording sleep electrophysiology, physiology, temperatures and behavior in the lab and ﬁeld", has authors "Bertrand Massot";
$connection77 (data: $source30, topic: $keyword45) isa connection;
$connection78 (data: $source30, topic: $keyword54) isa connection;
$connection79 (data: $source30, topic: $keyword78) isa connection;
$source22 isa source, has title "Detailed heart rate variability analysis in athletes", has authors "Orsolya Kiss";
$connection80 (data: $source22, topic: $keyword30) isa connection;
$connection81 (data: $source22, topic: $keyword31) isa connection;
$connection82 (data: $source22, topic: $keyword55) isa connection;
$connection83 (data: $source22, topic: $keyword56) isa connection;
$connection84 (data: $source22, topic: $keyword57) isa connection;
$source25 isa source, has title "Heart rate and high frequency heart rate variability during stress as biomarker for clinical depression. A systematic review", has authors "Carmen Schiweck";
$connection85 (data: $source25, topic: $keyword30) isa connection;
$connection86 (data: $source25, topic: $keyword42) isa connection;
$connection87 (data: $source25, topic: $keyword60) isa connection;
$connection88 (data: $source25, topic: $keyword62) isa connection;
$connection89 (data: $source25, topic: $keyword73) isa connection;
$source26 isa source, has title "Optimizing the use of biologgers for movement ecology research", has authors "Hannah J. Williams";
$connection90 (data: $source26, topic: $keyword45) isa connection;
$connection91 (data: $source26, topic: $keyword79) isa connection;
$connection92 (data: $source26, topic: $keyword80) isa connection;
$source42 isa source, has title "EFFECTS OF SHORT-TERM PSYCHOLOGICAL STRESS ON THE TIME AND FREQUENCY DOMAINS OF HEART-RATE VARIABILITY", has authors "J. P. A. DELANEY";
$connection93 (data: $source42, topic: $keyword30) isa connection;
$connection94 (data: $source42, topic: $keyword42) isa connection;
$connection95 (data: $source42, topic: $keyword73) isa connection;
$source43 isa source, has title "Isolated cortical computations during delta waves support memory consolidation", has authors "Michaël Zugaro";
$source38 isa source, has title "Sleep Ecophysiology: Integrating Neuroscience and Ecology", has authors "Anne E. Aulsebrook";
$connection96 (data: $source38, topic: $keyword54) isa connection;
$connection97 (data: $source38, topic: $keyword79) isa connection;
$connection98 (data: $source38, topic: $keyword81) isa connection;
$source33 isa source, has title "Stress Determined through Heart Rate Variability Predicts Immune Function", has authors "Hong Luo";
$connection99 (data: $source33, topic: $keyword30) isa connection;
$connection100 (data: $source33, topic: $keyword42) isa connection;
$connection101 (data: $source33, topic: $keyword64) isa connection;
$source44 isa source, has title "Spikes in the sleeping brain", has authors "Yuji Ikegaya";
$source48 isa source, has title "Experimental Tools to Study Molecular Recognition within the Nanoparticle Corona", has authors "Markita P. Landry";
$connection102 (data: $source48, topic: $keyword73) isa connection;
$source47 isa source, has title "Heart rate variability related to effort at work", has authors "Arja Uusitalo";
$connection103 (data: $source47, topic: $keyword73) isa connection;
$source49 isa source, has title "Effect of lecturing to 200 students on heart rate variability and alpha-amylase activity", has authors "Edith Filaire";
$connection104 (data: $source49, topic: $keyword73) isa connection;
$source51 isa source, has title "The perception of work stressors is related to reduced parasympathetic activity", has authors "Els Clays";
$connection105 (data: $source51, topic: $keyword73) isa connection;
$source52 isa source, has title "Effort–Reward Imbalance, Heart Rate, and Heart Rate Variability: The Cardiovascular Risk in Young Finns Study", has authors "Mirka Hintsanen";
$connection106 (data: $source52, topic: $keyword73) isa connection;
$source53 isa source, has title "Evaluation of the Cardiac Response to Psychological Stress by Short-Term ECG Recordings: Heart Rate Variability and Detrended Fluctuation Analysis", has authors "M. VargasLuna";
$connection107 (data: $source53, topic: $keyword73) isa connection;
$source54 isa source, has title "The effect of mental stress on heart rate variability and blood pressure during computer work", has authors "N. Hjortskov";
$connection108 (data: $source54, topic: $keyword73) isa connection;
$source55 isa source, has title "Cumulative stress and autonomic dysregulation in a community sample", has authors "Rachel Lampert";
$connection109 (data: $source55, topic: $keyword73) isa connection;
$source63 isa source, has title "Autonomic Tone as a Cardiovascular Risk Factor: The Dangers of Chronic Fight or Flight", has authors "Brian Curtis";
$connection110 (data: $source63, topic: $keyword73) isa connection;
$connection111 (data: $source63, topic: $keyword83) isa connection;
$connection112 (data: $source63, topic: $keyword30) isa connection;
$connection113 (data: $source63, topic: $keyword69) isa connection;
$connection114 (data: $source63, topic: $keyword77) isa connection;
$connection115 (data: $source63, topic: $keyword84) isa connection;
$connection116 (data: $source63, topic: $keyword42) isa connection;
$connection117 (data: $source63, topic: $keyword75) isa connection;
$source56 isa source, has title "Perceived Mental Stress and Reactions in Heart Rate Variability—A Pilot Study Among Employees of an Electronics Company", has authors "Reetta Orsila";
$connection118 (data: $source56, topic: $keyword73) isa connection;
$source58 isa source, has title "Gender difference in heart rate variability in medical students and association with the level of stress", has authors "Pushpanathan Punita";
$connection119 (data: $source58, topic: $keyword73) isa connection;
$source59 isa source, has title "Linking daily stress processes and laboratory-based heart rate variability in a national sample of midlife and older adults", has authors "Nancy L. Sin";
$connection120 (data: $source59, topic: $keyword73) isa connection;
$source60 isa source, has title "Children’s heart rate variability as stress indicator: Association with reported stress and cortisol", has authors "Nathalie Michels";
$connection121 (data: $source60, topic: $keyword73) isa connection;
$source50 isa source, has title "Development of an animal-borne blood sample collection device and its deployment for the determination of cardiovascular and stress hormones in phocid seals", has authors "Yoshio Takei";
$connection122 (data: $source50, topic: $keyword73) isa connection;
$source57 isa source, has title "Hemodynamic and Autonomic Adjustments to Real Life Stress Conditions in Humans", has authors "Daniela Lucini";
$connection123 (data: $source57, topic: $keyword73) isa connection;
$source64 isa source, has title "Central Command Neurons of the Sympathetic Nervous System: Basis of the Fight-or-Flight Response", has authors "Arthur D. Loewy";
$connection124 (data: $source64, topic: $keyword42) isa connection;
$connection125 (data: $source64, topic: $keyword77) isa connection;
$connection126 (data: $source64, topic: $keyword81) isa connection;
$connection127 (data: $source64, topic: $keyword83) isa connection;
$source66 isa source, has title "Fight-or-flight response", has authors "Wikipedia";
$connection128 (data: $source66, topic: $keyword42) isa connection;
$connection129 (data: $source66, topic: $keyword67) isa connection;
$connection130 (data: $source66, topic: $keyword77) isa connection;
$connection131 (data: $source66, topic: $keyword83) isa connection;
$connection132 (data: $source66, topic: $keyword84) isa connection;
$connection133 (data: $source66, topic: $keyword86) isa connection;
$source65 isa source, has title "Does “Fight or Flight” Need Updating?", has authors "Stefan Bracha";
$connection134 (data: $source65, topic: $keyword42) isa connection;
$connection135 (data: $source65, topic: $keyword83) isa connection;
