insert

$keyword3 isa keyword, has hashtag "Thalamus";
$keyword4 isa keyword, has hashtag "GlobusPallidus";
$keyword5 isa keyword, has hashtag "BasalGanglia";
$keyword6 isa keyword, has hashtag "MediumSpinyNeuron";
$keyword7 isa keyword, has hashtag "Neuron";
$keyword8 isa keyword, has hashtag "Disinhibition";
$keyword9 isa keyword, has hashtag "Calcium";
$keyword10 isa keyword, has hashtag "CerebralCortex";
$keyword11 isa keyword, has hashtag "ParkinsonsDisease";
$keyword12 isa keyword, has hashtag "Parkinsonism";
$keyword13 isa keyword, has hashtag "StandardModel";
$keyword14 isa keyword, has hashtag "SubstantiaNigra";
$keyword15 isa keyword, has hashtag "Walking";
$keyword16 isa keyword, has hashtag "Mouse";
$keyword17 isa keyword, has hashtag "Hypokinesia";
$keyword18 isa keyword, has hashtag "Constellation";
$keyword19 isa keyword, has hashtag "Frequency";
$keyword20 isa keyword, has hashtag "AfferentNerveFiber";
$keyword21 isa keyword, has hashtag "Brain";
$keyword22 isa keyword, has hashtag "DeepBrainStimulation";
$keyword23 isa keyword, has hashtag "Rotation";
$keyword24 isa keyword, has hashtag "AtomicNucleus";
$keyword25 isa keyword, has hashtag "Cerebellum";
$keyword26 isa keyword, has hashtag "GlutamicAcid";
$keyword27 isa keyword, has hashtag "CellNucleus";
$keyword28 isa keyword, has hashtag "Dendrite";
$keyword29 isa keyword, has hashtag "PyramidalCell";
$keyword30 isa keyword, has hashtag "Synapse";
$keyword31 isa keyword, has hashtag "AssociativeProperty";
$keyword32 isa keyword, has hashtag "MotorCortex";
$keyword33 isa keyword, has hashtag "Primate";
$keyword34 isa keyword, has hashtag "GammaAminobutyricAcid";
$keyword35 isa keyword, has hashtag "Integrator";
$keyword36 isa keyword, has hashtag "ActionSelection";
$keyword37 isa keyword, has hashtag "Habit";
$keyword38 isa keyword, has hashtag "Proprioception";
$keyword39 isa keyword, has hashtag "ApparentMagnitude";
$keyword40 isa keyword, has hashtag "AnatomicalTermsOfLocation";
$keyword41 isa keyword, has hashtag "Pharynx";
$keyword42 isa keyword, has hashtag "SupplementaryMotorArea";
$keyword43 isa keyword, has hashtag "Noise";
$keyword44 isa keyword, has hashtag "Dyskinesia";
$keyword45 isa keyword, has hashtag "LDOPA";
$keyword46 isa keyword, has hashtag "Paradox";
$keyword47 isa keyword, has hashtag "Muscle";
$keyword48 isa keyword, has hashtag "Patter";
$keyword49 isa keyword, has hashtag "Depolarization";
$keyword50 isa keyword, has hashtag "Dopamine";
$keyword51 isa keyword, has hashtag "Pathology";
$keyword52 isa keyword, has hashtag "Striatum";
$keyword53 isa keyword, has hashtag "EfferentNerveFiber";
$keyword54 isa keyword, has hashtag "Glutamatergic";
$keyword55 isa keyword, has hashtag "Tonic";
$keyword56 isa keyword, has hashtag "Ficus";
$keyword57 isa keyword, has hashtag "FeedForward";
$keyword58 isa keyword, has hashtag "SomatosensorySystem";
$keyword59 isa keyword, has hashtag "Curvature";
$keyword60 isa keyword, has hashtag "PrimaryMotorCortex";
$keyword61 isa keyword, has hashtag "DorsalRootGanglion";
$keyword62 isa keyword, has hashtag "MotorSystem";
$keyword63 isa keyword, has hashtag "Velocity";
$keyword64 isa keyword, has hashtag "MentalChronometry";
$keyword65 isa keyword, has hashtag "Basal";
$keyword66 isa keyword, has hashtag "Kinematics";
$keyword67 isa keyword, has hashtag "Amplitude";
$keyword68 isa keyword, has hashtag "Cognition";
$keyword69 isa keyword, has hashtag "Electromyography";
$keyword70 isa keyword, has hashtag "MotorControl";
$keyword71 isa keyword, has hashtag "ErrorDetectionAndCorrection";
$keyword72 isa keyword, has hashtag "Acceleration";
$keyword73 isa keyword, has hashtag "Energy";
$keyword74 isa keyword, has hashtag "HebbianTheory";
$keyword75 isa keyword, has hashtag "ChemicalSynapse";
$keyword76 isa keyword, has hashtag "Sensor";
$keyword77 isa keyword, has hashtag "Coupling";
$keyword78 isa keyword, has hashtag "Hertz";
$keyword79 isa keyword, has hashtag "Synchronization";
$keyword80 isa keyword, has hashtag "Summit";
$keyword81 isa keyword, has hashtag "TheBetaBand";
$keyword82 isa keyword, has hashtag "FrontalLobe";
$keyword83 isa keyword, has hashtag "PrefrontalCortex";
$keyword84 isa keyword, has hashtag "AnteriorCingulateCortex";
$keyword85 isa keyword, has hashtag "Discrimination";
$keyword86 isa keyword, has hashtag "Receptor";
$keyword87 isa keyword, has hashtag "Optogenetics";
$keyword88 isa keyword, has hashtag "SoundRecordingAndReproduction";
$keyword89 isa keyword, has hashtag "Virus";
$keyword90 isa keyword, has hashtag "Channelrhodopsin";
$keyword91 isa keyword, has hashtag "ActionPotential";
$keyword92 isa keyword, has hashtag "Latency";
$keyword93 isa keyword, has hashtag "Memory";
$keyword94 isa keyword, has hashtag "Oscillation";
$keyword95 isa keyword, has hashtag "MexicanCession";
$keyword96 isa keyword, has hashtag "Emergence";
$keyword97 isa keyword, has hashtag "SpinalCord";
$keyword98 isa keyword, has hashtag "PrimarySomatosensoryCortex";
$keyword99 isa keyword, has hashtag "Electroencephalography";
$keyword100 isa keyword, has hashtag "Magnitude";
$keyword101 isa keyword, has hashtag "GammaWave";
$keyword102 isa keyword, has hashtag "Sleep";
$keyword103 isa keyword, has hashtag "Hippocampus";
$keyword104 isa keyword, has hashtag "Neocortex";
$keyword105 isa keyword, has hashtag "PhaseModulation";
$keyword106 isa keyword, has hashtag "ThetaWave";
$keyword107 isa keyword, has hashtag "Entrainment";
$keyword108 isa keyword, has hashtag "MultiplicativeInverse";
$keyword109 isa keyword, has hashtag "Scalp";
$keyword110 isa keyword, has hashtag "InterplayEntertainment";
$keyword111 isa keyword, has hashtag "FrequencyBand";
$keyword112 isa keyword, has hashtag "Mode";
$keyword113 isa keyword, has hashtag "Hyperpolarization";
$keyword114 isa keyword, has hashtag "Overproduction";
$keyword115 isa keyword, has hashtag "NeuralOscillation";
$keyword116 isa keyword, has hashtag "LateralInhibition";
$keyword117 isa keyword, has hashtag "Retina";
$keyword118 isa keyword, has hashtag "EpisodicMemory";
$keyword119 isa keyword, has hashtag "ProceduralMemory";
$keyword120 isa keyword, has hashtag "Phase";
$keyword121 isa keyword, has hashtag "Ganglion";
$keyword122 isa keyword, has hashtag "Forebrain";
$keyword123 isa keyword, has hashtag "Spindle";
$keyword124 isa keyword, has hashtag "LimbicSystem";
$keyword125 isa keyword, has hashtag "Blockade";
$keyword126 isa keyword, has hashtag "Probability";
$keyword127 isa keyword, has hashtag "Stimulus";
$keyword128 isa keyword, has hashtag "Recall";
$keyword129 isa keyword, has hashtag "LowfrequencyOscillation";
$keyword130 isa keyword, has hashtag "Protein–proteinInteraction";
$keyword131 isa keyword, has hashtag "Schizophrenia";
$keyword132 isa keyword, has hashtag "Neuropsychiatry";
$keyword133 isa keyword, has hashtag "Epilepsy";
$keyword134 isa keyword, has hashtag "CellMembrane";
$keyword135 isa keyword, has hashtag "Broadband";
$keyword136 isa keyword, has hashtag "Narrowband";
$keyword137 isa keyword, has hashtag "Modulation";
$keyword138 isa keyword, has hashtag "Variance";
$keyword139 isa keyword, has hashtag "TimeSeries";
$keyword140 isa keyword, has hashtag "EventrelatedPotential";
$keyword141 isa keyword, has hashtag "VisualCortex";
$keyword142 isa keyword, has hashtag "SensoryNervousSystem";
$keyword143 isa keyword, has hashtag "Sound";
$keyword144 isa keyword, has hashtag "MembranePotential";
$keyword145 isa keyword, has hashtag "PhaseAngle";
$keyword146 isa keyword, has hashtag "HouseholdIncomeInTheUnitedStates";
$keyword147 isa keyword, has hashtag "CognitiveLoad";
$keyword148 isa keyword, has hashtag "Saccade";
$keyword149 isa keyword, has hashtag "Newsome";
$keyword150 isa keyword, has hashtag "RateFunction";
$keyword151 isa keyword, has hashtag "MusicalTuning";
$keyword152 isa keyword, has hashtag "Bridge";
$keyword153 isa keyword, has hashtag "Electrode";
$keyword154 isa keyword, has hashtag "Micrometre";
$keyword155 isa keyword, has hashtag "Vertebra";
$keyword156 isa keyword, has hashtag "SNR";
$keyword157 isa keyword, has hashtag "SignaltonoiseRatio";
$keyword158 isa keyword, has hashtag "Ageing";
$keyword159 isa keyword, has hashtag "Gait";
$keyword160 isa keyword, has hashtag "Dopaminergic";
$keyword161 isa keyword, has hashtag "Dementia";
$keyword162 isa keyword, has hashtag "Disability";
$keyword163 isa keyword, has hashtag "ExecutiveFunctions";
$keyword164 isa keyword, has hashtag "CorrelationAndDependence";
$keyword165 isa keyword, has hashtag "AlzheimersDisease";
$keyword166 isa keyword, has hashtag "Prodrug";
$keyword167 isa keyword, has hashtag "CircumstantialEvidence";
$keyword168 isa keyword, has hashtag "Dystonia";
$keyword169 isa keyword, has hashtag "Deconstruction";
$keyword170 isa keyword, has hashtag "Discharge";
$keyword171 isa keyword, has hashtag "Neuroplasticity";
$keyword172 isa keyword, has hashtag "Maze";
$keyword173 isa keyword, has hashtag "Neurology";
$keyword174 isa keyword, has hashtag "Syndrome";
$keyword175 isa keyword, has hashtag "Magnetoencephalography";
$keyword176 isa keyword, has hashtag "LocalField";
$source1 isa source, has title "Basal Ganglia output to the thalamus: still a paradox", has authors "Jesse H. Goldberg, Michael ...";
$connection1 (data: $source1, topic: $keyword3) isa connection;
$connection2 (data: $source1, topic: $keyword4) isa connection;
$connection3 (data: $source1, topic: $keyword5) isa connection;
$connection4 (data: $source1, topic: $keyword6) isa connection;
$connection5 (data: $source1, topic: $keyword7) isa connection;
$connection6 (data: $source1, topic: $keyword8) isa connection;
$connection7 (data: $source1, topic: $keyword9) isa connection;
$connection8 (data: $source1, topic: $keyword10) isa connection;
$connection9 (data: $source1, topic: $keyword11) isa connection;
$connection10 (data: $source1, topic: $keyword12) isa connection;
$connection11 (data: $source1, topic: $keyword13) isa connection;
$connection12 (data: $source1, topic: $keyword46) isa connection;
$source2 isa source, has title "Regulation of parkinsonian motor behaviors by optogenetic control of basal ganglia circuitry", has authors "Alexxai V. Kravitz, Benjami...";
$connection13 (data: $source2, topic: $keyword14) isa connection;
$connection14 (data: $source2, topic: $keyword15) isa connection;
$connection15 (data: $source2, topic: $keyword16) isa connection;
$connection16 (data: $source2, topic: $keyword6) isa connection;
$connection17 (data: $source2, topic: $keyword17) isa connection;
$connection18 (data: $source2, topic: $keyword18) isa connection;
$connection19 (data: $source2, topic: $keyword11) isa connection;
$connection20 (data: $source2, topic: $keyword87) isa connection;
$connection21 (data: $source2, topic: $keyword5) isa connection;
$source3 isa source, has title "Optical Deconstruction of Parkinsonian Neural Circuitry", has authors "Gradinaru";
$connection22 (data: $source3, topic: $keyword19) isa connection;
$connection23 (data: $source3, topic: $keyword20) isa connection;
$connection24 (data: $source3, topic: $keyword21) isa connection;
$connection25 (data: $source3, topic: $keyword22) isa connection;
$connection26 (data: $source3, topic: $keyword23) isa connection;
$connection27 (data: $source3, topic: $keyword169) isa connection;
$connection28 (data: $source3, topic: $keyword11) isa connection;
$source4 isa source, has title "Motor thalamus integration of cortical, cerebella and basal ganglia information: implications for normal and parkinsonian conditions", has authors "Bosch-Bouju";
$connection29 (data: $source4, topic: $keyword7) isa connection;
$connection30 (data: $source4, topic: $keyword14) isa connection;
$connection31 (data: $source4, topic: $keyword4) isa connection;
$connection32 (data: $source4, topic: $keyword10) isa connection;
$connection33 (data: $source4, topic: $keyword24) isa connection;
$connection34 (data: $source4, topic: $keyword5) isa connection;
$connection35 (data: $source4, topic: $keyword25) isa connection;
$connection36 (data: $source4, topic: $keyword26) isa connection;
$connection37 (data: $source4, topic: $keyword27) isa connection;
$connection38 (data: $source4, topic: $keyword28) isa connection;
$connection39 (data: $source4, topic: $keyword29) isa connection;
$connection40 (data: $source4, topic: $keyword20) isa connection;
$connection41 (data: $source4, topic: $keyword30) isa connection;
$connection42 (data: $source4, topic: $keyword31) isa connection;
$connection43 (data: $source4, topic: $keyword32) isa connection;
$connection44 (data: $source4, topic: $keyword3) isa connection;
$connection45 (data: $source4, topic: $keyword33) isa connection;
$connection46 (data: $source4, topic: $keyword34) isa connection;
$connection47 (data: $source4, topic: $keyword35) isa connection;
$connection48 (data: $source4, topic: $keyword36) isa connection;
$connection49 (data: $source4, topic: $keyword37) isa connection;
$connection50 (data: $source4, topic: $keyword38) isa connection;
$source5 isa source, has title "Neuronal Activity in the Primate Motor Thalamus During Visually Triggered and Internally Generated Limb Movements ", has authors "Donkelaar";
$connection51 (data: $source5, topic: $keyword5) isa connection;
$connection52 (data: $source5, topic: $keyword25) isa connection;
$connection53 (data: $source5, topic: $keyword4) isa connection;
$connection54 (data: $source5, topic: $keyword39) isa connection;
$connection55 (data: $source5, topic: $keyword40) isa connection;
$connection56 (data: $source5, topic: $keyword41) isa connection;
$connection57 (data: $source5, topic: $keyword3) isa connection;
$connection58 (data: $source5, topic: $keyword42) isa connection;
$connection59 (data: $source5, topic: $keyword33) isa connection;
$source6 isa source, has title "Pathophysiology of bradykinesia in Parkinson's disease", has authors "";
$connection60 (data: $source6, topic: $keyword5) isa connection;
$connection61 (data: $source6, topic: $keyword43) isa connection;
$connection62 (data: $source6, topic: $keyword11) isa connection;
$connection63 (data: $source6, topic: $keyword44) isa connection;
$connection64 (data: $source6, topic: $keyword45) isa connection;
$connection65 (data: $source6, topic: $keyword46) isa connection;
$connection66 (data: $source6, topic: $keyword4) isa connection;
$connection67 (data: $source6, topic: $keyword14) isa connection;
$connection68 (data: $source6, topic: $keyword10) isa connection;
$connection69 (data: $source6, topic: $keyword3) isa connection;
$connection70 (data: $source6, topic: $keyword17) isa connection;
$source7 isa source, has title "The basal ganglia: focused selection and inhibition of competing motor programs", has authors "Mink";
$connection71 (data: $source7, topic: $keyword5) isa connection;
$connection72 (data: $source7, topic: $keyword10) isa connection;
$connection73 (data: $source7, topic: $keyword25) isa connection;
$connection74 (data: $source7, topic: $keyword47) isa connection;
$source8 isa source, has title "Control of Basal Ganglia Output by Direct and Indirect Pathway Projection Neurons", has authors "Freeze";
$connection75 (data: $source8, topic: $keyword48) isa connection;
$connection76 (data: $source8, topic: $keyword6) isa connection;
$connection77 (data: $source8, topic: $keyword5) isa connection;
$connection78 (data: $source8, topic: $keyword14) isa connection;
$connection79 (data: $source8, topic: $keyword49) isa connection;
$connection80 (data: $source8, topic: $keyword30) isa connection;
$source9 isa source, has title "Competition between feedback loops underlies normal and pathological dynamics in the basal ganglia", has authors "Leblois";
$connection81 (data: $source9, topic: $keyword10) isa connection;
$connection82 (data: $source9, topic: $keyword4) isa connection;
$connection83 (data: $source9, topic: $keyword50) isa connection;
$connection84 (data: $source9, topic: $keyword5) isa connection;
$connection85 (data: $source9, topic: $keyword51) isa connection;
$connection86 (data: $source9, topic: $keyword52) isa connection;
$connection87 (data: $source9, topic: $keyword11) isa connection;
$source10 isa source, has title "Thalamus plays a central role in ongoing cortical functioning", has authors "";
$connection88 (data: $source10, topic: $keyword3) isa connection;
$connection89 (data: $source10, topic: $keyword10) isa connection;
$connection90 (data: $source10, topic: $keyword53) isa connection;
$connection91 (data: $source10, topic: $keyword54) isa connection;
$connection92 (data: $source10, topic: $keyword55) isa connection;
$connection93 (data: $source10, topic: $keyword56) isa connection;
$source11 isa source, has title "Consensus paper: roles of the cerebellum in motor control—the diversity of ideas on cerebellar involvement in movement", has authors "Manto";
$connection94 (data: $source11, topic: $keyword25) isa connection;
$connection95 (data: $source11, topic: $keyword47) isa connection;
$connection96 (data: $source11, topic: $keyword57) isa connection;
$connection97 (data: $source11, topic: $keyword58) isa connection;
$connection98 (data: $source11, topic: $keyword51) isa connection;
$connection99 (data: $source11, topic: $keyword59) isa connection;
$connection100 (data: $source11, topic: $keyword60) isa connection;
$connection101 (data: $source11, topic: $keyword21) isa connection;
$connection102 (data: $source11, topic: $keyword32) isa connection;
$connection103 (data: $source11, topic: $keyword5) isa connection;
$connection104 (data: $source11, topic: $keyword61) isa connection;
$connection105 (data: $source11, topic: $keyword62) isa connection;
$source12 isa source, has title "Changes in the Control of Arm Position, Movement, and Thalamic Discharge During Local Inactivation in the Globus Pallidus of the Monkey", has authors "Inase";
$connection106 (data: $source12, topic: $keyword63) isa connection;
$connection107 (data: $source12, topic: $keyword64) isa connection;
$connection108 (data: $source12, topic: $keyword55) isa connection;
$connection109 (data: $source12, topic: $keyword4) isa connection;
$connection110 (data: $source12, topic: $keyword10) isa connection;
$connection111 (data: $source12, topic: $keyword32) isa connection;
$connection112 (data: $source12, topic: $keyword170) isa connection;
$source13 isa source, has title "Basal Ganglia Contributions to Motor Control: A Vigorous Tutor", has authors "Turner";
$connection113 (data: $source13, topic: $keyword4) isa connection;
$connection114 (data: $source13, topic: $keyword10) isa connection;
$connection115 (data: $source13, topic: $keyword5) isa connection;
$connection116 (data: $source13, topic: $keyword65) isa connection;
$connection117 (data: $source13, topic: $keyword7) isa connection;
$connection118 (data: $source13, topic: $keyword66) isa connection;
$connection119 (data: $source13, topic: $keyword64) isa connection;
$connection120 (data: $source13, topic: $keyword20) isa connection;
$connection121 (data: $source13, topic: $keyword3) isa connection;
$connection122 (data: $source13, topic: $keyword67) isa connection;
$connection123 (data: $source13, topic: $keyword68) isa connection;
$connection124 (data: $source13, topic: $keyword52) isa connection;
$connection125 (data: $source13, topic: $keyword69) isa connection;
$connection126 (data: $source13, topic: $keyword70) isa connection;
$connection127 (data: $source13, topic: $keyword71) isa connection;
$connection128 (data: $source13, topic: $keyword63) isa connection;
$connection129 (data: $source13, topic: $keyword72) isa connection;
$connection130 (data: $source13, topic: $keyword73) isa connection;
$connection131 (data: $source13, topic: $keyword21) isa connection;
$connection132 (data: $source13, topic: $keyword74) isa connection;
$connection133 (data: $source13, topic: $keyword75) isa connection;
$source14 isa source, has title "Cerebellar influence on motor cortex plasticity: behavioral implications for Parkinson’s disease", has authors "Kishore";
$connection134 (data: $source14, topic: $keyword25) isa connection;
$connection135 (data: $source14, topic: $keyword76) isa connection;
$connection136 (data: $source14, topic: $keyword32) isa connection;
$connection137 (data: $source14, topic: $keyword171) isa connection;
$connection138 (data: $source14, topic: $keyword11) isa connection;
$source15 isa source, has title "The cortico-basal ganglia integrative network: the role of the thalamus", has authors "Haber";
$connection139 (data: $source15, topic: $keyword10) isa connection;
$connection140 (data: $source15, topic: $keyword121) isa connection;
$connection141 (data: $source15, topic: $keyword3) isa connection;
$source16 isa source, has title "From intentions to actions: Neural oscillations encode motor processes through phase, amplitude and phase-amplitude coupling", has authors "Etienne Combrisson";
$connection142 (data: $source16, topic: $keyword77) isa connection;
$connection143 (data: $source16, topic: $keyword60) isa connection;
$connection144 (data: $source16, topic: $keyword67) isa connection;
$connection145 (data: $source16, topic: $keyword78) isa connection;
$connection146 (data: $source16, topic: $keyword79) isa connection;
$connection147 (data: $source16, topic: $keyword80) isa connection;
$connection148 (data: $source16, topic: $keyword81) isa connection;
$connection149 (data: $source16, topic: $keyword82) isa connection;
$connection150 (data: $source16, topic: $keyword83) isa connection;
$connection151 (data: $source16, topic: $keyword40) isa connection;
$connection152 (data: $source16, topic: $keyword84) isa connection;
$connection153 (data: $source16, topic: $keyword85) isa connection;
$connection154 (data: $source16, topic: $keyword19) isa connection;
$connection155 (data: $source16, topic: $keyword115) isa connection;
$source17 isa source, has title "Optogenetic Stimulation of Frontal D1 Neurons Compensates for Impaired Temporal Control of Action in Dopamine-Depleted Mice", has authors "Young-Cho Kim";
$connection156 (data: $source17, topic: $keyword82) isa connection;
$connection157 (data: $source17, topic: $keyword7) isa connection;
$connection158 (data: $source17, topic: $keyword50) isa connection;
$connection159 (data: $source17, topic: $keyword86) isa connection;
$connection160 (data: $source17, topic: $keyword87) isa connection;
$connection161 (data: $source17, topic: $keyword88) isa connection;
$connection162 (data: $source17, topic: $keyword89) isa connection;
$connection163 (data: $source17, topic: $keyword90) isa connection;
$connection164 (data: $source17, topic: $keyword91) isa connection;
$connection165 (data: $source17, topic: $keyword92) isa connection;
$connection166 (data: $source17, topic: $keyword93) isa connection;
$source18 isa source, has title "Neural oscillations: beta band activity across motor networks", has authors "Preeya Khanna 1 and Jose M ...";
$connection167 (data: $source18, topic: $keyword69) isa connection;
$connection168 (data: $source18, topic: $keyword58) isa connection;
$connection169 (data: $source18, topic: $keyword94) isa connection;
$connection170 (data: $source18, topic: $keyword29) isa connection;
$connection171 (data: $source18, topic: $keyword32) isa connection;
$connection172 (data: $source18, topic: $keyword95) isa connection;
$connection173 (data: $source18, topic: $keyword40) isa connection;
$connection174 (data: $source18, topic: $keyword21) isa connection;
$connection175 (data: $source18, topic: $keyword96) isa connection;
$connection176 (data: $source18, topic: $keyword60) isa connection;
$connection177 (data: $source18, topic: $keyword97) isa connection;
$connection178 (data: $source18, topic: $keyword98) isa connection;
$connection179 (data: $source18, topic: $keyword99) isa connection;
$connection180 (data: $source18, topic: $keyword100) isa connection;
$connection181 (data: $source18, topic: $keyword101) isa connection;
$connection182 (data: $source18, topic: $keyword10) isa connection;
$connection183 (data: $source18, topic: $keyword52) isa connection;
$connection184 (data: $source18, topic: $keyword102) isa connection;
$connection185 (data: $source18, topic: $keyword64) isa connection;
$connection186 (data: $source18, topic: $keyword115) isa connection;
$connection187 (data: $source18, topic: $keyword81) isa connection;
$source19 isa source, has title "Entrainment of Neocortical Neurons and Gamma Oscillations by the Hippocampal Theta Rhythm", has authors "Anton Sirota, Sean Montgome...";
$connection188 (data: $source19, topic: $keyword103) isa connection;
$connection189 (data: $source19, topic: $keyword104) isa connection;
$connection190 (data: $source19, topic: $keyword10) isa connection;
$connection191 (data: $source19, topic: $keyword19) isa connection;
$connection192 (data: $source19, topic: $keyword7) isa connection;
$connection193 (data: $source19, topic: $keyword101) isa connection;
$connection194 (data: $source19, topic: $keyword105) isa connection;
$connection195 (data: $source19, topic: $keyword106) isa connection;
$connection196 (data: $source19, topic: $keyword107) isa connection;
$connection197 (data: $source19, topic: $keyword108) isa connection;
$source20 isa source, has title "High Thalamocortical Theta Coherence in Patients with Parkinson’s Disease", has authors "Johannes Sarnthein and Dani...";
$connection198 (data: $source20, topic: $keyword10) isa connection;
$connection199 (data: $source20, topic: $keyword3) isa connection;
$connection200 (data: $source20, topic: $keyword78) isa connection;
$connection201 (data: $source20, topic: $keyword99) isa connection;
$connection202 (data: $source20, topic: $keyword109) isa connection;
$connection203 (data: $source20, topic: $keyword100) isa connection;
$connection204 (data: $source20, topic: $keyword110) isa connection;
$connection205 (data: $source20, topic: $keyword19) isa connection;
$connection206 (data: $source20, topic: $keyword7) isa connection;
$connection207 (data: $source20, topic: $keyword111) isa connection;
$connection208 (data: $source20, topic: $keyword77) isa connection;
$connection209 (data: $source20, topic: $keyword112) isa connection;
$connection210 (data: $source20, topic: $keyword113) isa connection;
$connection211 (data: $source20, topic: $keyword114) isa connection;
$connection212 (data: $source20, topic: $keyword115) isa connection;
$connection213 (data: $source20, topic: $keyword116) isa connection;
$connection214 (data: $source20, topic: $keyword117) isa connection;
$connection215 (data: $source20, topic: $keyword11) isa connection;
$source21 isa source, has title "Learning-related coordination of striatal and hippocampal theta rhythms during acquisition of a procedural maze task", has authors "William E. DeCoteau, Cather...";
$connection216 (data: $source21, topic: $keyword52) isa connection;
$connection217 (data: $source21, topic: $keyword103) isa connection;
$connection218 (data: $source21, topic: $keyword93) isa connection;
$connection219 (data: $source21, topic: $keyword118) isa connection;
$connection220 (data: $source21, topic: $keyword119) isa connection;
$connection221 (data: $source21, topic: $keyword120) isa connection;
$connection222 (data: $source21, topic: $keyword121) isa connection;
$connection223 (data: $source21, topic: $keyword65) isa connection;
$connection224 (data: $source21, topic: $keyword122) isa connection;
$connection225 (data: $source21, topic: $keyword172) isa connection;
$source22 isa source, has title "Oscillatory Entrainment of Striatal Neurons in Freely Moving Rats", has authors "Joshua D. Berke, Murat Okat...";
$connection226 (data: $source22, topic: $keyword123) isa connection;
$connection227 (data: $source22, topic: $keyword106) isa connection;
$connection228 (data: $source22, topic: $keyword78) isa connection;
$connection229 (data: $source22, topic: $keyword40) isa connection;
$connection230 (data: $source22, topic: $keyword52) isa connection;
$connection231 (data: $source22, topic: $keyword7) isa connection;
$connection232 (data: $source22, topic: $keyword103) isa connection;
$connection233 (data: $source22, topic: $keyword19) isa connection;
$connection234 (data: $source22, topic: $keyword98) isa connection;
$connection235 (data: $source22, topic: $keyword107) isa connection;
$connection236 (data: $source22, topic: $keyword68) isa connection;
$connection237 (data: $source22, topic: $keyword124) isa connection;
$connection238 (data: $source22, topic: $keyword5) isa connection;
$connection239 (data: $source22, topic: $keyword50) isa connection;
$connection240 (data: $source22, topic: $keyword125) isa connection;
$connection241 (data: $source22, topic: $keyword126) isa connection;
$source23 isa source, has title "Human memory strength is predicted by theta-frequency phase-locking of single neurons", has authors "Ueli Rutishauser, Ian B. Ro...";
$connection242 (data: $source23, topic: $keyword127) isa connection;
$connection243 (data: $source23, topic: $keyword30) isa connection;
$connection244 (data: $source23, topic: $keyword106) isa connection;
$connection245 (data: $source23, topic: $keyword67) isa connection;
$connection246 (data: $source23, topic: $keyword128) isa connection;
$connection247 (data: $source23, topic: $keyword93) isa connection;
$connection248 (data: $source23, topic: $keyword7) isa connection;
$source24 isa source, has title "THETA-RHYTHMICALLY FIRING NEURONS IN THE ANTERIOR THALAMUS: IMPLICATIONS FOR MNEMONIC FUNCTIONS OF PAPEZ'S CIRCUIT", has authors "R. P. VERTES, Z. ALBO and G...";
$connection249 (data: $source24, topic: $keyword40) isa connection;
$connection250 (data: $source24, topic: $keyword3) isa connection;
$connection251 (data: $source24, topic: $keyword7) isa connection;
$connection252 (data: $source24, topic: $keyword27) isa connection;
$connection253 (data: $source24, topic: $keyword103) isa connection;
$connection254 (data: $source24, topic: $keyword106) isa connection;
$source25 isa source, has title "Thalamocortical dysrhythmia: A neurological and neuropsychiatric syndrome characterized by magnetoencephalography", has authors "Rodolfo R. Llinas, Urs Riba...";
$connection255 (data: $source25, topic: $keyword3) isa connection;
$connection256 (data: $source25, topic: $keyword10) isa connection;
$connection257 (data: $source25, topic: $keyword113) isa connection;
$connection258 (data: $source25, topic: $keyword9) isa connection;
$connection259 (data: $source25, topic: $keyword11) isa connection;
$connection260 (data: $source25, topic: $keyword106) isa connection;
$connection261 (data: $source25, topic: $keyword12) isa connection;
$connection262 (data: $source25, topic: $keyword4) isa connection;
$connection263 (data: $source25, topic: $keyword129) isa connection;
$connection264 (data: $source25, topic: $keyword130) isa connection;
$connection265 (data: $source25, topic: $keyword131) isa connection;
$connection266 (data: $source25, topic: $keyword132) isa connection;
$connection267 (data: $source25, topic: $keyword52) isa connection;
$connection268 (data: $source25, topic: $keyword133) isa connection;
$connection269 (data: $source25, topic: $keyword134) isa connection;
$connection270 (data: $source25, topic: $keyword173) isa connection;
$connection271 (data: $source25, topic: $keyword174) isa connection;
$connection272 (data: $source25, topic: $keyword175) isa connection;
$source26 isa source, has title "Broadband Shifts in Local Field Potential Power Spectra Are Correlated with Single-Neuron Spiking in Humans", has authors "Jeremy R. Manning, Joshua J...";
$connection273 (data: $source26, topic: $keyword135) isa connection;
$connection274 (data: $source26, topic: $keyword7) isa connection;
$connection275 (data: $source26, topic: $keyword136) isa connection;
$connection276 (data: $source26, topic: $keyword137) isa connection;
$connection277 (data: $source26, topic: $keyword19) isa connection;
$connection278 (data: $source26, topic: $keyword94) isa connection;
$connection279 (data: $source26, topic: $keyword138) isa connection;
$connection280 (data: $source26, topic: $keyword139) isa connection;
$source27 isa source, has title "Ongoing EEG phase as a trial-by-trial predictor of perceptual and attentional variability", has authors "R. VanRullen, N. A. Busch, ...";
$connection281 (data: $source27, topic: $keyword78) isa connection;
$connection282 (data: $source27, topic: $keyword7) isa connection;
$connection283 (data: $source27, topic: $keyword127) isa connection;
$connection284 (data: $source27, topic: $keyword99) isa connection;
$connection285 (data: $source27, topic: $keyword140) isa connection;
$connection286 (data: $source27, topic: $keyword19) isa connection;
$connection287 (data: $source27, topic: $keyword64) isa connection;
$connection288 (data: $source27, topic: $keyword141) isa connection;
$connection289 (data: $source27, topic: $keyword21) isa connection;
$connection290 (data: $source27, topic: $keyword100) isa connection;
$connection291 (data: $source27, topic: $keyword142) isa connection;
$connection292 (data: $source27, topic: $keyword143) isa connection;
$connection293 (data: $source27, topic: $keyword144) isa connection;
$connection294 (data: $source27, topic: $keyword145) isa connection;
$connection295 (data: $source27, topic: $keyword146) isa connection;
$connection296 (data: $source27, topic: $keyword147) isa connection;
$connection297 (data: $source27, topic: $keyword68) isa connection;
$connection298 (data: $source27, topic: $keyword85) isa connection;
$connection299 (data: $source27, topic: $keyword148) isa connection;
$connection300 (data: $source27, topic: $keyword137) isa connection;
$source28 isa source, has title "Local field potentials indicate network state and account for neuronal response variability", has authors "Ryan C. Kelly, Matthew A. S...";
$connection301 (data: $source28, topic: $keyword127) isa connection;
$connection302 (data: $source28, topic: $keyword91) isa connection;
$connection303 (data: $source28, topic: $keyword43) isa connection;
$connection304 (data: $source28, topic: $keyword149) isa connection;
$connection305 (data: $source28, topic: $keyword150) isa connection;
$connection306 (data: $source28, topic: $keyword151) isa connection;
$connection307 (data: $source28, topic: $keyword10) isa connection;
$connection308 (data: $source28, topic: $keyword152) isa connection;
$connection309 (data: $source28, topic: $keyword30) isa connection;
$connection310 (data: $source28, topic: $keyword153) isa connection;
$connection311 (data: $source28, topic: $keyword144) isa connection;
$connection312 (data: $source28, topic: $keyword7) isa connection;
$connection313 (data: $source28, topic: $keyword154) isa connection;
$connection314 (data: $source28, topic: $keyword155) isa connection;
$connection315 (data: $source28, topic: $keyword19) isa connection;
$connection316 (data: $source28, topic: $keyword156) isa connection;
$connection317 (data: $source28, topic: $keyword157) isa connection;
$connection318 (data: $source28, topic: $keyword176) isa connection;
$source29 isa source, has title "Early, untreated Parkinson’s disease patients show reaction time variability", has authors "Richard M. Camicioli, Margu...";
$connection319 (data: $source29, topic: $keyword64) isa connection;
$connection320 (data: $source29, topic: $keyword68) isa connection;
$connection321 (data: $source29, topic: $keyword158) isa connection;
$connection322 (data: $source29, topic: $keyword159) isa connection;
$connection323 (data: $source29, topic: $keyword50) isa connection;
$connection324 (data: $source29, topic: $keyword137) isa connection;
$connection325 (data: $source29, topic: $keyword160) isa connection;
$connection326 (data: $source29, topic: $keyword161) isa connection;
$connection327 (data: $source29, topic: $keyword162) isa connection;
$connection328 (data: $source29, topic: $keyword92) isa connection;
$connection329 (data: $source29, topic: $keyword163) isa connection;
$connection330 (data: $source29, topic: $keyword164) isa connection;
$connection331 (data: $source29, topic: $keyword165) isa connection;
$connection332 (data: $source29, topic: $keyword11) isa connection;
$source30 isa source, has title "Gamma oscillations in the human basal ganglia", has authors "Ned Jenkinson, Andrea A. Ku...";
$connection333 (data: $source30, topic: $keyword101) isa connection;
$connection334 (data: $source30, topic: $keyword160) isa connection;
$connection335 (data: $source30, topic: $keyword164) isa connection;
$connection336 (data: $source30, topic: $keyword67) isa connection;
$connection337 (data: $source30, topic: $keyword78) isa connection;
$connection338 (data: $source30, topic: $keyword5) isa connection;
$connection339 (data: $source30, topic: $keyword44) isa connection;
$connection340 (data: $source30, topic: $keyword11) isa connection;
$connection341 (data: $source30, topic: $keyword66) isa connection;
$connection342 (data: $source30, topic: $keyword3) isa connection;
$connection343 (data: $source30, topic: $keyword50) isa connection;
$connection344 (data: $source30, topic: $keyword166) isa connection;
$connection345 (data: $source30, topic: $keyword45) isa connection;
$connection346 (data: $source30, topic: $keyword32) isa connection;
$connection347 (data: $source30, topic: $keyword79) isa connection;
$connection348 (data: $source30, topic: $keyword40) isa connection;
$connection349 (data: $source30, topic: $keyword167) isa connection;
$connection350 (data: $source30, topic: $keyword168) isa connection;